server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: authservice
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: emplservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/employees**
            
  security:
    jwt:
      secret: ebd7b9c9993a32f5b7d022006963395a0ecbba5348461d09ff3aa48f8812b966